/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sayyid Muhammad Habib
 */
public class Tugas_Stack extends javax.swing.JFrame {
    private String mobil[] = {"/<default package/fiat_500_50px.png/","/<default package/sedan_50px.png/"};
    private int top=-1;
    private int size=7;

    /**
     * Creates new form Tugas_Stack
     */
    
    /**public Tugas_Stack(int kapasitas){
        size = kapasitas;
        top = -1;
        mobil = new String [size];
    }*/
    
    public boolean isEmpty(){
        return top == -1;
    }
    
    public boolean isFull(){
        return top == size-1;
    }
    
    public void push(){
        if(isFull()){
            txt_pengumuman.setText("Maaf Parkir Penuh");
        }
        else if(top==-1){
            top++;
            txt_mobil1.setText(plat_mbl.getText().toUpperCase());
            mobil_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sedan_50px.png")));
            txt_pengumuman.setText("");
        }
        else if(top==0){
            top++;
            txt_mobil2.setText(plat_mbl.getText().toUpperCase());
            mobil_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fiat_500_50px.png")));
            txt_pengumuman.setText("");
        }
        else if(top==1){
            top++;
            txt_mobil3.setText(plat_mbl.getText().toUpperCase());
            mobil_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sedan_50px.png")));
            txt_pengumuman.setText("");
        }
        else if(top==2){
            top++;
            txt_mobil4.setText(plat_mbl.getText().toUpperCase());
            mobil_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fiat_500_50px.png")));
            txt_pengumuman.setText("");
            
        }
        else if(top==3){
            top++;
            txt_mobil5.setText(plat_mbl.getText().toUpperCase());
            mobil_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sedan_50px.png")));
            txt_pengumuman.setText("");
        }
        else if(top==4){
            top++;
            txt_mobil6.setText(plat_mbl.getText().toUpperCase());
            mobil_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fiat_500_50px.png")));
            txt_pengumuman.setText("");
        }
        else if(top==5){
            top++;
            txt_mobil7.setText(plat_mbl.getText().toUpperCase());
            mobil_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sedan_50px.png")));
            txt_pengumuman.setText("");
        }
    }
    
    public void pop(){
        if(isEmpty()){
            txt_pengumuman.setText("Parkir sudah kosong");
        }
        else if(top==6){
            top--;
            txt_mobil7.setText("");
            mobil_7.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==5){
            top--;
            txt_mobil6.setText("");
            mobil_6.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==4){
            top--;
            txt_mobil5.setText("");
            mobil_5.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==3){
            top--;
            txt_mobil4.setText("");
            mobil_4.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==2){
            top--;
            txt_mobil3.setText("");
            mobil_3.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==1){
            top--;
            txt_mobil2.setText("");
            mobil_2.setIcon(null);
            txt_pengumuman.setText("");
        }
        else if(top==0){
            top--;
            txt_mobil1.setText("");
            mobil_1.setIcon(null);
            txt_pengumuman.setText("");
        }
        
    }
    
    public Tugas_Stack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mobil_7 = new javax.swing.JLabel();
        mobil_1 = new javax.swing.JLabel();
        mobil_3 = new javax.swing.JLabel();
        mobil_2 = new javax.swing.JLabel();
        mobil_4 = new javax.swing.JLabel();
        mobil_5 = new javax.swing.JLabel();
        mobil_6 = new javax.swing.JLabel();
        txt_mobil1 = new javax.swing.JLabel();
        txt_mobil2 = new javax.swing.JLabel();
        txt_mobil3 = new javax.swing.JLabel();
        txt_mobil4 = new javax.swing.JLabel();
        txt_mobil5 = new javax.swing.JLabel();
        txt_mobil6 = new javax.swing.JLabel();
        txt_mobil7 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        btn_masuk = new javax.swing.JButton();
        plat_mbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_pengumuman = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobil_7.setBackground(new java.awt.Color(102, 255, 255));
        mobil_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 60));

        mobil_1.setBackground(new java.awt.Color(102, 255, 255));
        mobil_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        mobil_3.setBackground(new java.awt.Color(102, 255, 255));
        mobil_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 60));

        mobil_2.setBackground(new java.awt.Color(102, 255, 255));
        mobil_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_2.setText(" ");
        mobil_2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 60));

        mobil_4.setBackground(new java.awt.Color(102, 255, 255));
        mobil_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 60));

        mobil_5.setBackground(new java.awt.Color(102, 255, 255));
        mobil_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 60));

        mobil_6.setBackground(new java.awt.Color(102, 255, 255));
        mobil_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobil_6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        jPanel2.add(mobil_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 80, 60));

        txt_mobil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil1.setText(" ");
        jPanel2.add(txt_mobil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 80, -1));

        txt_mobil2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil2.setText(" ");
        jPanel2.add(txt_mobil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 46, 80, -1));

        txt_mobil3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil3.setText(" ");
        jPanel2.add(txt_mobil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 46, 80, -1));

        txt_mobil4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil4.setText(" ");
        jPanel2.add(txt_mobil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 46, 80, -1));

        txt_mobil5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil5.setText(" ");
        jPanel2.add(txt_mobil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 46, 80, -1));

        txt_mobil6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil6.setText(" ");
        jPanel2.add(txt_mobil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 46, 80, -1));

        txt_mobil7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mobil7.setText(" ");
        jPanel2.add(txt_mobil7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 46, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 60));

        btn_keluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 80, 50));

        btn_masuk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_masuk.setText("Masuk");
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        jPanel1.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 80, 50));

        plat_mbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plat_mbl.setText(" ");
        jPanel1.add(plat_mbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 100, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No. Plat Mobil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 100, -1));

        txt_pengumuman.setBackground(new java.awt.Color(153, 153, 153));
        txt_pengumuman.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txt_pengumuman.setForeground(new java.awt.Color(153, 255, 255));
        txt_pengumuman.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_pengumuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 410, 60));

        jPanel3.setBackground(new java.awt.Color(102, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel2.setText("Selamat Datang");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 270, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kendaraan Roda Empat");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 650, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Di Aplikasi Parkiran Seri");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/road_50px.png"))); // NOI18N
        jLabel4.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(666, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
                pop();
                
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
                push();
                plat_mbl.setText("");      
        
    }//GEN-LAST:event_btn_masukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas_Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas_Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas_Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas_Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas_Stack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mobil_1;
    private javax.swing.JLabel mobil_2;
    private javax.swing.JLabel mobil_3;
    private javax.swing.JLabel mobil_4;
    private javax.swing.JLabel mobil_5;
    private javax.swing.JLabel mobil_6;
    private javax.swing.JLabel mobil_7;
    private javax.swing.JTextField plat_mbl;
    private javax.swing.JLabel txt_mobil1;
    private javax.swing.JLabel txt_mobil2;
    private javax.swing.JLabel txt_mobil3;
    private javax.swing.JLabel txt_mobil4;
    private javax.swing.JLabel txt_mobil5;
    private javax.swing.JLabel txt_mobil6;
    private javax.swing.JLabel txt_mobil7;
    private javax.swing.JTextField txt_pengumuman;
    // End of variables declaration//GEN-END:variables
}
